// <auto-generated />
using DataVisual.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataVisual.Migrations
{
    [DbContext(typeof(FDDataContext))]
    partial class FDDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DataVisual.Data.FD1RUL", b =>
                {
                    b.Property<int>("EngineID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("RUL")
                        .HasColumnType("int");

                    b.HasKey("EngineID");

                    b.ToTable("FD1RULs");
                });

            modelBuilder.Entity("DataVisual.Data.FD1TEST", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cycle")
                        .HasColumnType("int");

                    b.Property<int>("EngineID")
                        .HasColumnType("int");

                    b.Property<float>("SensorData_1")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_10")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_11")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_12")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_13")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_14")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_15")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_16")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_17")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_18")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_19")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_2")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_20")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_21")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_3")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_4")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_5")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_6")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_7")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_8")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_9")
                        .HasColumnType("real");

                    b.Property<float>("Setting_1")
                        .HasColumnType("real");

                    b.Property<float>("Setting_2")
                        .HasColumnType("real");

                    b.Property<float>("Setting_3")
                        .HasColumnType("real");

                    b.HasKey("ID");

                    b.ToTable("FD1TESTs");
                });

            modelBuilder.Entity("DataVisual.Data.FD1TRAIN", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cycle")
                        .HasColumnType("int");

                    b.Property<int>("EngineID")
                        .HasColumnType("int");

                    b.Property<float>("SensorData_1")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_10")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_11")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_12")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_13")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_14")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_15")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_16")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_17")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_18")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_19")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_2")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_20")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_21")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_3")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_4")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_5")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_6")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_7")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_8")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_9")
                        .HasColumnType("real");

                    b.Property<float>("Setting_1")
                        .HasColumnType("real");

                    b.Property<float>("Setting_2")
                        .HasColumnType("real");

                    b.Property<float>("Setting_3")
                        .HasColumnType("real");

                    b.HasKey("ID");

                    b.ToTable("FD1TRAINs");
                });

            modelBuilder.Entity("DataVisual.Data.FD2RUL", b =>
                {
                    b.Property<int>("EngineID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("RUL")
                        .HasColumnType("int");

                    b.HasKey("EngineID");

                    b.ToTable("FD2RULs");
                });

            modelBuilder.Entity("DataVisual.Data.FD2TEST", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cycle")
                        .HasColumnType("int");

                    b.Property<int>("EngineID")
                        .HasColumnType("int");

                    b.Property<float>("SensorData_1")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_10")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_11")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_12")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_13")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_14")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_15")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_16")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_17")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_18")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_19")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_2")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_20")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_21")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_3")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_4")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_5")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_6")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_7")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_8")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_9")
                        .HasColumnType("real");

                    b.Property<float>("Setting_1")
                        .HasColumnType("real");

                    b.Property<float>("Setting_2")
                        .HasColumnType("real");

                    b.Property<float>("Setting_3")
                        .HasColumnType("real");

                    b.HasKey("ID");

                    b.ToTable("FD2TESTs");
                });

            modelBuilder.Entity("DataVisual.Data.FD2TRAIN", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cycle")
                        .HasColumnType("int");

                    b.Property<int>("EngineID")
                        .HasColumnType("int");

                    b.Property<float>("SensorData_1")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_10")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_11")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_12")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_13")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_14")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_15")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_16")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_17")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_18")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_19")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_2")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_20")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_21")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_3")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_4")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_5")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_6")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_7")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_8")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_9")
                        .HasColumnType("real");

                    b.Property<float>("Setting_1")
                        .HasColumnType("real");

                    b.Property<float>("Setting_2")
                        .HasColumnType("real");

                    b.Property<float>("Setting_3")
                        .HasColumnType("real");

                    b.HasKey("ID");

                    b.ToTable("FD2TRAINs");
                });

            modelBuilder.Entity("DataVisual.Data.FD3RUL", b =>
                {
                    b.Property<int>("EngineID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("RUL")
                        .HasColumnType("int");

                    b.HasKey("EngineID");

                    b.ToTable("FD3RULs");
                });

            modelBuilder.Entity("DataVisual.Data.FD3TEST", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cycle")
                        .HasColumnType("int");

                    b.Property<int>("EngineID")
                        .HasColumnType("int");

                    b.Property<float>("SensorData_1")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_10")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_11")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_12")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_13")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_14")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_15")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_16")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_17")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_18")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_19")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_2")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_20")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_21")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_3")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_4")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_5")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_6")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_7")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_8")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_9")
                        .HasColumnType("real");

                    b.Property<float>("Setting_1")
                        .HasColumnType("real");

                    b.Property<float>("Setting_2")
                        .HasColumnType("real");

                    b.Property<float>("Setting_3")
                        .HasColumnType("real");

                    b.HasKey("ID");

                    b.ToTable("FD3TESTs");
                });

            modelBuilder.Entity("DataVisual.Data.FD3TRAIN", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cycle")
                        .HasColumnType("int");

                    b.Property<int>("EngineID")
                        .HasColumnType("int");

                    b.Property<float>("SensorData_1")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_10")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_11")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_12")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_13")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_14")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_15")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_16")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_17")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_18")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_19")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_2")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_20")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_21")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_3")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_4")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_5")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_6")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_7")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_8")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_9")
                        .HasColumnType("real");

                    b.Property<float>("Setting_1")
                        .HasColumnType("real");

                    b.Property<float>("Setting_2")
                        .HasColumnType("real");

                    b.Property<float>("Setting_3")
                        .HasColumnType("real");

                    b.HasKey("ID");

                    b.ToTable("FD3TRAINs");
                });

            modelBuilder.Entity("DataVisual.Data.FD4RUL", b =>
                {
                    b.Property<int>("EngineID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("RUL")
                        .HasColumnType("int");

                    b.HasKey("EngineID");

                    b.ToTable("FD4RULs");
                });

            modelBuilder.Entity("DataVisual.Data.FD4TEST", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cycle")
                        .HasColumnType("int");

                    b.Property<int>("EngineID")
                        .HasColumnType("int");

                    b.Property<float>("SensorData_1")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_10")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_11")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_12")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_13")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_14")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_15")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_16")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_17")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_18")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_19")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_2")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_20")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_21")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_3")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_4")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_5")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_6")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_7")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_8")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_9")
                        .HasColumnType("real");

                    b.Property<float>("Setting_1")
                        .HasColumnType("real");

                    b.Property<float>("Setting_2")
                        .HasColumnType("real");

                    b.Property<float>("Setting_3")
                        .HasColumnType("real");

                    b.HasKey("ID");

                    b.ToTable("FD4TESTs");
                });

            modelBuilder.Entity("DataVisual.Data.FD4TRAIN", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cycle")
                        .HasColumnType("int");

                    b.Property<int>("EngineID")
                        .HasColumnType("int");

                    b.Property<float>("SensorData_1")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_10")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_11")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_12")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_13")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_14")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_15")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_16")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_17")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_18")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_19")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_2")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_20")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_21")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_3")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_4")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_5")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_6")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_7")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_8")
                        .HasColumnType("real");

                    b.Property<float>("SensorData_9")
                        .HasColumnType("real");

                    b.Property<float>("Setting_1")
                        .HasColumnType("real");

                    b.Property<float>("Setting_2")
                        .HasColumnType("real");

                    b.Property<float>("Setting_3")
                        .HasColumnType("real");

                    b.HasKey("ID");

                    b.ToTable("FD4TRAINs");
                });
#pragma warning restore 612, 618
        }
    }
}
